### ISSUE TITLE
Misalignment of Code Editor Highlight Box

### ISSUE THREAD

**Issue by princerajpoot20** [asyncapi/studio#861]
### Problem
<img width="545" alt="Screenshot 2023-11-25 at 12 57 09 PM" src="https://github.com/asyncapi/studio/assets/44585452/725ba5cb-bced-4489-94a8-753727bfb609">
 

The highlight box for the `code editor` mode in the `EditorSwitch` component is not centered and spills out of the boundary.

#### Viewing the Issue
See it here: [Link](https://deploy-preview-859--asyncapi-studio-design-system.netlify.app/?path=/story/components-editorswitch--code-editor)

#### Expectation
It should be perfectly aligned.

**Comment by KhudaDad414** [comment]
@princerajpoot20 In which environment is it not centred? I am using Chrome and it is centred for me. 🤔

**Comment by princerajpoot20** [comment]
@KhudaDad414 In Chrome on my system, it is not centered. In Safari, it is centered correctly, but the inner symbol are not visible. In Brave, it is displayed perfectly.

Chrome:
<img width="1312" alt="Screenshot 2023-11-30 at 9 55 04 PM" src="https://github.com/asyncapi/studio/assets/44585452/c367bbca-d9b8-49e7-a285-a9001fca14cd">
Safari: 
<img width="516" alt="Screenshot 2023-11-30 at 10 03 34 PM" src="https://github.com/asyncapi/studio/assets/44585452/f5e81ad2-5f48-45d5-8fdf-389d1e16563a">
Brave: 
<img width="516" alt="Screenshot 2023-11-30 at 10 04 17 PM" src="https://github.com/asyncapi/studio/assets/44585452/6bfa68bf-078d-4197-b86f-a412f40e8a44">

**Comment by adityagarg06** [comment]
For chrome, it is perfectly aligned:
![image](https://github.com/asyncapi/studio/assets/104292766/afbfee20-cd72-4c2c-bb0b-8c48bdc85359)

I think the issue has been resolved.

**Comment by nikhil-3112** [comment]
![Screenshot (179)](https://github.com/asyncapi/studio/assets/98270496/db2d9de7-dc0a-4260-8fa7-5f66ad627aeb)

On Chrome and Opera browsers it is perfectly aligned. There is no issue with the alignment of the highlight box.
Issue Resolved.

**Comment by Amzani** [comment]
@princerajpoot20 you still see this issue ?

**Comment by princerajpoot20** [comment]
@Amzani Yes, the issue is still there.
Link used in the browser: https://deploy-preview-978--asyncapi-studio-design-system.netlify.app/?path=/story/components-editorswitch--c

https://github.com/asyncapi/studio/assets/44585452/03db918b-eb3b-4456-a4fc-bce8f3a06637

**Comment by KhudaDad414** [comment]
@princerajpoot20 since I can't reproduce it on my environment (tried with 3 browsers and it's centred.) can you open a PR with a fix?

**Comment by princerajpoot20** [comment]
@KhudaDad414 Sure.

**Comment by lmgyuan** [comment]
@princerajpoot20 could it be that your chrome version is not updated? (Just a thought) browsers make all kinds of mistakes.
